const ADD_TO_CART = 'cart:ADD_TO_CART';
const REMOVE_FROM_CART = 'cart:REMOVE_FROM_CART';
const CHECKOUT_CART = 'cart:CHECKOUT_CART';
const RESET_CART = 'cart:RESET_CART';
const GET_CACHED_CART = 'cart:GET_CACHED_CART';

export {
	ADD_TO_CART,
	REMOVE_FROM_CART,
	CHECKOUT_CART,
	RESET_CART,
	GET_CACHED_CART,
};
