const GET_PRODUCTS = {
	REQUEST: 'product:GET_PRODUCTS:REQUEST',
	SUCCESS: 'product:GET_PRODUCTS:SUCCESS',
	FAIL: 'product:GET_PRODUCTS:FAIL',
};

const GET_PRODUCT_DETAIL = {
	REQUEST: 'product:GET_PRODUCT_DETAIL:REQUEST',
	SUCCESS: 'product:GET_PRODUCT_DETAIL:SUCCESS',
	FAIL: 'product:GET_PRODUCT_DETAIL:FAIL',
};

export { GET_PRODUCTS, GET_PRODUCT_DETAIL };
